export default [
  { id: 1, nome: 'Augusto', login: 'augusto', senha: '10' },
  { id: 2, nome: 'Kauã', login: 'kauã', senha: '20' },
  { id: 3, nome: 'José', login: 'jose', senha: '30' },
  { id: 4, nome: 'Henrique', login: 'henrique', senha: '40' },
  { id: 5, nome: 'João', login: 'joao', senha: '50' },
  { id: 6, nome: 'Maria', login: 'maria', senha: '60' },
  { id: 7, nome: 'Alberto', login: 'alberto', senha: '70' },
  { id: 8, nome: 'Joana', login: 'joana', senha: '80' },
  { id: 9, nome: 'Lucas', login: 'lucas', senha: '90' },
  { id: 10, nome: 'Pedro', login: 'pedro', senha: '10' },
  { id: 11, nome: 'Renan', login: 'renan', senha: '20' },
  { id: 12, nome: 'Paulo', login: 'paulo', senha: '30' },
  { id: 13, nome: 'Matheus', login: 'matheus', senha: '40' },
  { id: 14, nome: 'Bruno', login: 'bruno', senha: '50' },
  { id: 15, nome: 'Alessandro', login: 'alessandro', senha: '60' },
  { id: 16, nome: 'Luana', login: 'luana', senha: '70' },
  { id: 17, nome: 'Anderson', login: 'anderson', senha: '80' },
  { id: 18, nome: 'Thiago', login: 'thiago', senha: '90' },
  { id: 19, nome: 'Júlia', login: 'julia', senha: '10' },
  { id: 20, nome: 'Angelina', login: 'angelina', senha: '20' },
  { id: 21, nome: 'Ruan', login: 'ruan', senha: '30' },
  { id: 22, nome: 'Albertina', login: 'albertina', senha: '40' },
  { id: 23, nome: 'Helena', login: 'helena', senha: '50' },
  { id: 24, nome: 'Vitor', login: 'vitor', senha: '60' },
  { id: 25, nome: 'Marcos', login: 'marcos', senha: '70' },
];